### ISSUE TITLE
 Error when try to run --use-txt

### ISSUE THREAD

**Issue by Plutogithub2022** [Godofcoffe/FisherMan#11]
secureuser@EagleEye:~/FisherMan$ python3 fisherman.py --use-txt id1.txt

    ______    _             __                    __  ___                
   / ____/   (_)   _____   / /_   ___    _____   /  |/  /  ____ _   ____ 
  / /_      / /   / ___/  / __ \ / _ \  / ___/  / /|_/ /  / __ `/  / __ \
 / __/     / /   (__  )  / / / //  __/ / /     / /  / /  / /_/ /  / / / /
/_/       /_/   /____/  /_/ /_/ \___/ /_/     /_/  /_/   \__,_/  /_/ /_/ 

[*] logging into the account: gmarquizn@gmail.com
Traceback (most recent call last):
  File "fisherman.py", line 102, in <module>
    little_fish._scrape(browser, little_fish.entry(cli.txt))
  File "/home/secureuser/FisherMan/src/fisherman/FisherMan.py", line 228, in entry
    self.__upload_txt_file(*args)
  File "/home/secureuser/FisherMan/src/fisherman/FisherMan.py", line 205, in __upload_txt_file
    if not name_file.endswith(".txt").lower():
AttributeError: 'bool' object has no attribute 'lower'

**Comment by Godofcoffe** [comment]
Thanks for reporting, the problem seems to me to be quite simple. I will release the patch soon.
