### ISSUE TITLE
”time limit exceeded”

### ISSUE THREAD

**Issue by stianz** [Godofcoffe/FisherMan#9]
![f](https://user-images.githubusercontent.com/100744512/156289929-5620932c-569c-4df9-a879-3ba98eda7df3.png)
The message "time limit exceeded" is displayed and the system does not work properly.
fisherman.py 3.7.1
Windows 10 Pro

**Comment by Godofcoffe** [comment]
I am already in the science of this, the ghost account was blocked, I had to create another one, and I am still refactoring all the code.

**Comment by Godofcoffe** [comment]
I won't change the functionality, I will just add a few more things and improve the maintainability and execution of the code.

**Comment by Godofcoffe** [comment]
It's in testing now and minor corrections, on Monday I'll post it, if you want to check out what's new, you can go to my twitter at: https://twitter.com/robotnyte

**Comment by Godofcoffe** [comment]
I have already released the new version, you can now git clone it.
